### ISSUE TITLE
Attractive Readme file

### ISSUE THREAD

**Issue by Gautam-Arora24** [Gautam-Arora24/Covid-Tracker#2]
Need an attractive Readme.md file.

**Comment by tewarig** [comment]
hi, I would like to work on that.

**Comment by Gautam-Arora24** [comment]
@tewarig Go Ahead. And kindly include some sort of SVG's also. Make sure fork the repo :)

**Comment by tewarig** [comment]
sure, thanks

**Comment by tewarig** [comment]
https://github.com/Gautam-Arora24/Covid-Tracker/pull/3

**Comment by Gautam-Arora24** [comment]
Ya.. Sure

**Comment by Gautam-Arora24** [comment]
Awesome work @tewarig
